branch-defaults:
  default:
    environment: koajs-example
    group_suffix: null
environment-defaults:
  koajs-example:
    branch: null
    repository: null
global:
  application_name: koajs-example
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
